#
# These are services which are build on Lagoon
#

services:

  cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: cli
    labels:
      lagoon.type: cli-persistent
      lagoon.persistent.name: nginx # mount the persistent storage of nginx into this container
      lagoon.persistent: /app/public/sites/default/files/ # location where the persistent storage should be mounted

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/public/sites/default/files/ # define where the persistent storage should be mounted too

  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.name: nginx # we want this service be part of the nginx pod in Lagoon
      lagoon.persistent: /app/public/sites/default/files/ # define where the persistent storage should be mounted too

  mariadb:
    image: uselagoon/mariadb-10.6-drupal:latest
    labels:
      lagoon.type: mariadb
