config_rewrite:
  replace: [
    'dependencies.module',
    'hidden'
  ]
dependencies:
  module:
    - allowed_formats
    - hdbt_admin_tools
    - helfi_tpr
    - media_library
    - metatag
    - paragraphs
    - path
    - readonly_field_widget
    - text
    - select2
content:
  field_categories:
    type: readonly_field_widget
    weight: 39
    region: content
    settings:
      label: above
      formatter_type: null
      formatter_settings: { }
      show_description: false
    third_party_settings: { }
  field_hs_front_page:
    type: entity_reference_autocomplete
    weight: 31
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: { }
  field_ontologyword_details:
    type: readonly_field_widget
    weight: 40
    region: content
    settings:
      label: above
      formatter_type: null
      formatter_settings: {  }
      show_description: false
    third_party_settings: {  }
  field_study_field:
    type: select2_entity_reference
    weight: 31
    region: content
    settings:
      width: 100%
      autocomplete: false
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: { }
  hide_description:
    type: boolean_checkbox
    weight: 18
    region: content
    settings:
      display_label: true
    third_party_settings: { }
  subgroup:
    type: readonly_field_widget
    weight: 40
    region: content
    settings:
      label: above
      formatter_type: null
      formatter_settings: {  }
      show_description: false
    third_party_settings: {  }
hidden:
  created: true
  field_districts: true
  ontologyword_ids: true
